spring:  
  profiles: es1

server:
  port: 7070
  
eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress} #eureka1 
#    preferIpAddress: true  #当猜测主机名时，应该使用服务器的IP地址对操作系统所报告的主机名进行响应。
    instance-id: ${eureka.instance.hostname}:${server.port} #${eureka.instance.hostname}:${spring.cloud.client.ipAddress}:${server.port}  #服务实例的唯一标识，优先使用这个配置项，如果该项不指定，则可以指定metadataMap.instanceId

---
spring:  
  profiles: es2

server:
  port: 7071
  
eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress} #eureka2
    instance-id: ${eureka.instance.hostname}:${server.port}
    
---
spring:  
  profiles: es3

server:
  port: 7072
  
eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress} #eureka3
    instance-id: ${eureka.instance.hostname}:${server.port}
