spring:  
  profiles: es1

server:
  port: 7070
  
endpoints:
  shutdown:
    enabled: true #该属性是由actuator提供的操作控制类的endpoint，用于关闭应用
  
eureka:
  instance:
    hostname: eureka1 #${spring.cloud.client.ipAddress}
#    appname: eureka-server-01 #eureka内对应的serviceId，默认取spring.application.name的值
#    lease-renewal-interval-in-seconds: 30 #续约更新时间间隔（默认30秒）
#    lease-expiration-duration-in-seconds: 90  #续约到期时间（默认90秒）
#    preferIpAddress: true  #当猜测主机名时，应该使用服务器的IP地址对操作系统所报告的主机名进行响应。
    instance-id: ${eureka.instance.hostname}:${spring.cloud.client.ipAddress}:${server.port} #${eureka.instance.hostname}:${spring.cloud.client.ipAddress}:${server.port}  #服务实例的唯一标识，优先使用这个配置项，如果该项不指定，则可以指定metadataMap.instanceId
#    metadataMap:
#      instanceId: ${eureka.instance.hostname}:${spring.cloud.client.ipAddress}:${server.port}
#  server:
#    enable-self-preservation: false #关闭保护机制  
#    eviction-interval-timer-in-ms: 60*1000 #清理间隔（单位毫秒，默认是60*1000）
#  client:
#    register-with-eureka: false #是否要注册到服务器端，因为此处为Eureka Server，所以设定为false
#    fetch-registry: false  #是否从服务器端取得注册信息，因为此处为Eureka Server，所以设定为false
#    service-url:
#      defaultZone: http://eureka2:7071/eureka/,http://eureka3:7072/eureka/

---
spring:  
  profiles: es2

server:
  port: 7071
  
eureka:
  instance:
    hostname: eureka2
    instance-id: ${eureka.instance.hostname}:${spring.cloud.client.ipAddress}:${server.port}
    
---
spring:  
  profiles: es3

server:
  port: 7072
  
eureka:
  instance:
    hostname: eureka3
    instance-id: ${eureka.instance.hostname}:${spring.cloud.client.ipAddress}:${server.port}
